name: CVE Python Script

on:
  push:
    branches: "**"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime requests
    - name: Run Script
      run: |
        mkdir report
        python cve_report.py > report/cve_report.csv
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: report_download
        path: report

